/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent_of_code_2022.day1

import kotlin.test.Test
import kotlin.test.assertEquals

class Day1Test {
    @Test fun day1A() {
        assertEquals("67016", Day1A.calculateResult())
    }

    @Test fun day1B() {
        assertEquals("200116", Day1B.calculateResult())
    }
}
