/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent_of_code_2022

import advent_of_code_2022.day1

fun getEnvVar(key: String) = System.getenv(key) ?: exitWithMessage("Please set env var $key")

fun exitWithMessage(message: String) : Nothing {
    println(message)
    kotlin.system.exitProcess(1)
}

class Commands(val commandTypeName: String) : HashMap<String, () -> Unit>() {
    fun runCommand(key: String) =
        when (val command = this.get(key)) {
            null -> exitWithMessage("$commandTypeName must be one of: ${this.keys.joinToString()}")
            else -> command()
        }

    fun register(key: String, value: () -> Unit) = apply {
        this[key] = value
    }
}

val commands = Commands("Day")
    .register("1", day1.A)
    .register("1B", day1.B)

fun main() {
    val day = getEnvVar("DAY")
    commands.runCommand(day)
}