/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent_of_code_2022

import java.io.File

fun getEnvVar(key: String) = System.getenv(key) ?: exitWithMessage("Please set env var $key")

fun exitWithMessage(message: String) : Nothing {
    println(message)
    kotlin.system.exitProcess(1)
}

class Days {
    companion object :  HashMap<String, (String) -> String>() {
        fun runCommand(key: String) : String {
            val command = this.get(key) ?: exitWithMessage("Days must be one of: ${this.keys.joinToString()}")
            val filename = makeFilename(key)
            val input = readInput(filename)
            return command(input)
        }

        private fun makeFilename(key: String) = "[^0-9]+$".toRegex().replace(key, "")

        private fun readInput(name: String) = File("src/input", "$name.txt")
            .readText()

        fun register(key: String, value: (String) -> String) = apply {
            this[key] = value
        }

        init {
            Days
                .register("1A", day1A)
                .register("1B", day1B)
                .register("2A", day2A)
                .register("2B", day2B)
        }
    }
}



fun main() {
    val day = getEnvVar("DAY")
    println(Days.runCommand(day))
}