/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent_of_code_2022

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        assertNotNull(1)
    }
}
