package advent_of_code_2022/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test fun testDays() {
        mapOf(
            "1A" to "67016",
            "1B" to "200116",
        ).forEach {(k, v) ->
            assertEquals(v, Days.runCommand(k))
        }
    }
}
